name: Release Asset Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install zip and rsync
      run: sudo apt-get install zip rsync

    - name: Create required directory structure
      run: |
        mkdir wc-hide-shipping-methods
        rsync -av --exclude='wc-hide-shipping-methods' ./* wc-hide-shipping-methods/

    - name: Zip the project
      run: zip -r wc-hide-shipping-methods.zip wc-hide-shipping-methods/

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./wc-hide-shipping-methods.zip
        asset_name: wc-hide-shipping-methods.zip
        asset_content_type: application/zip
